/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The STABLE `pixtuoid sources --json` wire contract the Raycast extension
 * parses. Deliberately a flat DTO, NOT the internal `ConnectionRow` (whose
 * shape is a UI concern free to change).
 */
export interface SourceStatus {
  id: string;
  display_name: string;
  connected: boolean;
  cli_present: boolean;
  /**
   * The source's worst install or decode issue as one line, or `null` if none.
   */
  health?: string | null;
}
