/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One `{id, outcome, message?}` row of the `--json` batch envelope
 * `connect`/`disconnect`/`sources set` print.
 *
 * Treat this wire as PUBLISHED: installed Raycast store copies parse it
 * independently of the binary's version, so a further shape change needs a
 * version handshake, never another flag-day edit. The token spelling is pinned
 * by `change_outcome_wire_tokens_are_stable`.
 */
export interface OutcomeRow {
  /**
   * The registry source id the outcome applies to (e.g. `codex`).
   */
  id: string;
  /**
   * The bare machine token; human text rides in `message`.
   */
  outcome: "connected" | "disconnected" | "no_op" | "failed";
  /**
   * Human-readable detail, present exactly when the outcome carries any
   * (`failed`) and OMITTED rather than `null` otherwise.
   */
  message?: string | null;
}
