#!/usr/bin/env python3
"""Upstream wire-format drift watch.

pixtuoid decodes agent-CLI wire formats (hook event names, the subagent-dispatch
tool name, transcript type tags) whose names change upstream WITHOUT notice — the
`Task` -> `Agent` rename shipped undocumented and silently disabled subagent
suppression. This verifies that every name we depend on still exists at its
canonical upstream source, reading what we depend on from our OWN source (no
snapshot file to rot).

Findings carry a DISPOSITION (see `Report`), because "upstream changed" and "our
probe missed" need different work and only one of them is a statement about
upstream. Every document swept for name-presence declares an ANCHOR (see
`ANCHORS`) proving it is still the document that owns those names — no anchor, no
sweep: a stale pin that still returns 200 as a re-export facade otherwise reads as
mass drift, and #793's report would have renamed three WORKING env vars.

Exit codes:
  0  no findings
  1  actionable (verified drift, a review ping, OR probe health — all three need
     a human) -> open a tracking issue
  2  could not check (network/HTTP error) -> transient, do NOT alarm
"""

from __future__ import annotations

import dataclasses
import http.client
import json
import pathlib
import re
import sys
import traceback
import typing
import urllib.error
import urllib.request

# URLError alone is not enough: the READ phase inside fetch() raises raw
# socket.timeout / ConnectionResetError (OSError, NOT URLError) and
# http.client.IncompleteRead (HTTPException) — left uncaught they exit 1 and the
# workflow files a junk drift-titled issue from an empty report.
FETCH_ERRORS = (urllib.error.URLError, OSError, http.client.HTTPException)

# A permanent status means OUR pinned path is gone, so the watch is BLIND for that
# source: probe health, never transient. The trap it guards: `HTTPError` subclasses
# `URLError` ⊂ FETCH_ERRORS, so a 404 used to bucket as transient and the weekly
# job stayed green while silently watching nothing.
PERMANENT_HTTP_STATUS = frozenset({404, 410, 451})

REPO = pathlib.Path(__file__).resolve().parent.parent

# The two emitted halves of the drift surface. Each is generated by a test in the
# crate that OWNS those names (`src/drift_surface.rs`), so the watcher never
# parses our source: the crate fails its own test rather than this file silently
# reading a smaller set. Registration and decoding are separate documents because
# they answer different questions — see the `*_EVENTS` sharp edge in
# `crates/pixtuoid/SHARP-EDGES.md`.
CORE_LIB_FRAGMENT = "crates/pixtuoid-core/drift-surface.json"
CORE_BIN_FRAGMENT = "crates/pixtuoid/drift-surface.json"

# The ROLLOUT `response_item` types live in the sibling models.rs
# (`crate::models::ResponseItem`), NOT protocol.rs.
CC_TOOLS_URL = "https://code.claude.com/docs/en/tools-reference.md"
CC_HOOKS_URL = "https://code.claude.com/docs/en/hooks.md"

# Documented hooks.md surfaces the burn-tier decoder DEPENDS on: a string
# VANISHING here is review-class drift (the docs renamed a surface we read).
CC_DEPENDED_DOC_MARKERS = {
    "CLAUDE_EFFORT": "the hook-payload effort surface (effort.level, burn tier)",
    "receive a `model` field": "SessionStart's optional model field (burn tier)",
}

# APPEARANCE watch, the inverse direction: these are ABSENT from hooks.md today
# and a HIT is review-class (a surface to adopt), never breaking. CC is a closed
# binary, so the docs are the only watchable surface. `session_end` is snake_case
# on purpose — the SessionEnd HOOK name is all over hooks.md and must not match.
# Adopting a structural end record also means the liveness-probe first-sight
# bypass (`probe_admits`, core's source/jsonl.rs) needs an ended-check: it skips
# the gate's ended tail-scan only because no such marker exists.
CC_LIFECYCLE_SURFACE_MARKERS = {
    "session_end": 'a structural transcript end record (subtype:"session_end")',
    ".claude/sessions/": "the ~/.claude/sessions/<pid>.json session registry",
    "procStart": "the sessions-registry procStart field",
    # The CC decoder synthesizes effort labels from these undocumented markers;
    # documenting them upstream is a ping to re-verify our synthesized shape.
    "ultra_effort_enter": "the ultra-effort transcript attachment marker",
    "ultrathink_effort": "the ultrathink transcript attachment marker",
    "ultra_effort_exit": "the ultra-effort EXIT attachment marker (instant flame-off)",
}


# Registered hermes events for which upstream treating them as BLOCKING would let
# our silent exit 0 ANSWER a decision rather than merely observe one. Only the
# approval gate qualifies today; `pre_tool_call` is blocking upstream and that is
# fine — a tool gate is not a permission answer.




# Payload fields decode_rx_hook_payload reads — a renamed json tag silently
# zeroes the decode (`event`/`cwd` are load-bearing: a payload lacking them is
# rejected as malformed).



# CodeWhale ENV-MODE identity: the DEEPSEEK_* names our shim folds into the
# cwd-keyed envelope, set by `HookContext::to_env_vars`. WORKSPACE is
# load-bearing — it becomes the envelope `cwd` = the AgentId KEY, so a rename
# drops EVERY session (no sprite). DEEPSEEK_SESSION_ID is deliberately NOT read
# (proven inconsistent), and the raw subagent-JSON fields are left to the
# decoder's own parentless-degrade because a fuzzy `json!` macro owns them.

# ONE-DIRECTIONAL: opencode emits far more EventV2 types than we map, so a new
# upstream event is noise; only a type WE DEPEND ON vanishing alarms. Track the
# `dev` branch (the active default) and `packages/schema/` (the old
# `packages/core` path is a re-export shim that 200s but greps empty).

# `permission.asked` is decoded DEFENSIVELY (a V1/alias spelling); only
# `permission.v2.asked` is a guaranteed standalone upstream EventV2 definition, so
# don't alarm if the bare form isn't found as a `type:` literal.

# Payload FIELD names decode_oc_hook_payload reads, as `field:` property lines in
# the schema Struct defs. A rename → the decoder reads None → wrong-register /
# no-link / no-activity.

# Deliberately UNPINNED: the bare unpkg path 302-redirects to the latest
# published version, and a drift watch wants the latest shape, not a frozen one.
# The schema ships inside the platform packages (`@github/copilot` itself is now a
# loader stub); linux-x64 matches the CI host and every platform package carries
# an identical copy. ONE-DIRECTIONAL like opencode: only a depended type vanishing
# alarms.
COPILOT_SCHEMA_URL = "https://unpkg.com/@github/copilot-linux-x64/schemas/session-events.schema.json"

# Payload FIELD names decode_copilot_line / extract_copilot_cwd read, CURATED —
# not scraped, which would drag in opaque tool-arg keys and fixture JSON. `data`
# is the envelope every other field below lives under, so renaming that one key
# nulls all of them while the nested names still resolve (the all-depth union
# check would NOT alarm). The wire `parentId` is deliberately absent: sub-agents
# link via the envelope `agentId`, so watching it would alarm on a non-dependency.
COPILOT_PAYLOAD_FIELDS = {
    "data",
    "agentId", "sessionId", "context", "cwd",
    "toolCallId", "toolName", "arguments", "agentDisplayName",
    "permissionRequest", "result", "kind",
    "model",
}

# Cursor is a closed binary, so — like CC — the docs are the only watchable
# surface. ONE-DIRECTIONAL: only a depended event vanishing alarms. The
# common-word event `stop` is intrinsically low-confidence (the page contains the
# word regardless), so its disappearance can be masked; the distinctive
# `sessionStart`/`sessionEnd`/`preToolUse`/`postToolUse` carry the check.
CURSOR_HOOKS_URL = "https://cursor.com/docs/hooks"

# The canonical OpenClaw hook-name union, as quoted string literals.
# ONE-DIRECTIONAL: a hook WE REGISTER vanishing means the plugin registers
# something OpenClaw never fires, so the mascot silently goes dark.

# Payload FIELD names decode_openclaw_hook_payload reads: `runId` (the in-flight run
# key), `sessionId` (fallback key + label), `success` (agent_end → Degraded gate).
# `success` is a common word, so a rename of it could be masked by an unrelated
# occurrence; the distinctive `runId`/`sessionId` carry the check.
# Reads that are deliberately NOT watched, per source. The pattern the event
# sweeps already use: a `.get()` that is neither watched nor ledgered fails
# `no_decoder_read_is_unaccounted_for`, so adding one forces the decision instead
# of silently losing coverage — which is how `sessionId` and `extra` came to be
# missing from the two sets above.


# The gateway PORT is pixtuoid's runtime identity for one gateway, read off
# `gateway_start`'s event/ctx: a rename leaves every envelope stamped with the
# registration-time FALLBACK, so two live gateways collapse onto one mascot. The
# type names are watched instead of the common word `port`.

# The plugin cannot IMPORT upstream's `DEFAULT_GATEWAY_PORT` (it lives in
# OpenClaw's state dir, outside any `node_modules/openclaw`), so the literal is
# copied into `openclaw_plugin.js` — a copied constant is a latent drift bug
# unless something watches it. This is that watch.

# BOTH directions ride `VALID_HOOKS`, the declaration that OWNS the vocabulary,
# with `SHELL_UNSUPPORTED_HOOKS` naming which of those a SHELL hook cannot serve.
# The vanish half used to read `_DEFAULT_PAYLOADS` one file over — the `hermes
# hooks test` FIXTURE set, which does not list every hook — and filed a verified
# ⛔ against `pre_approval_request`, an event this repo holds a capture of.
# The shell-hook PAYLOAD is assembled by `_serialize_payload()` in a DIFFERENT
# file from the event list — two orthogonal checks, two files.
# Field names decode_hermes_hook_payload reads, as dict-key literals in
# _serialize_payload; a rename → the JSON omits it → the decoder reads None.
# `hermes::resolve_hermes_home` MIRRORS `_hermes_home_from_env`. ONE-DIRECTIONAL:
# a depended env var VANISHING means we resolve a config.yaml hermes no longer
# reads — the #880 fail-silent class, whose only symptom is a missing sprite.
# The `.strip()` and the `%LOCALAPPDATA%\hermes` SHAPE are behaviour, not names,
# so they are pinned by the hermes unit tests instead.

# Kimi is a pnpm/TS monorepo, but the canonical hook-event list lives in the docs
# (each name appears verbatim in the summary table AND the payload examples), so —
# like Cursor — the raw markdown is the watchable surface. ONE-DIRECTIONAL. The
# common-word event `Stop` is intrinsically low-confidence (the doc contains the
# word regardless); the distinctive PascalCase names carry the check.
KIMI_HOOKS_URL = (
    "https://raw.githubusercontent.com/MoonshotAI/kimi-code/main/"
    "docs/en/customization/hooks.md"
)

# `RolloutItem` lives in the history crate, NOT protocol.rs — a stale pin here goes
# blind rather than wrong, which reads as green.

# grok pins `features = ["unstable"]`, so its real ACP surface is the UNION of the
# v1 stable + v1 unstable tag sets — hence two fetches. v2 is a separate, partly
# non-overlapping line grok does NOT speak, so fetching it would emit false
# "adopt terminal_update" noise.
ACP_V1_SCHEMA_URL = (
    "https://raw.githubusercontent.com/agentclientprotocol/"
    "agent-client-protocol/main/schema/v1/schema.json"
)

ACP_V1_SCHEMA_UNSTABLE_URL = (
    "https://raw.githubusercontent.com/agentclientprotocol/"
    "agent-client-protocol/main/schema/v1/schema.unstable.json"
)

# Three depended surfaces in three files: the hook event enum + payload serde,
# the transcript xAI-extension vocabulary, and the active_sessions.json
# liveness-registry struct.
# The module that WRITES the method into updates.jsonl (`serialize_entry("method",
# XAI_SESSION_UPDATE_METHOD)`), so it owns the name we gate on — not the
# notification module, which only mentions it in a `///`.
# Matches BOTH sides of this watch — upstream's declaration and our mirror of it.
# The value must be read from the declaration, never scanned for as a substring:
# a rename of the VALUE at the declaration leaves the old literal standing in a
# `///` and a `#[cfg(test)]` fixture, so `"…" in text` never fires.



# Hook fields decode_grok_hook_payload reads, split by serde origin: ENVELOPE
# fields are camelCase via struct-level rename_all, so the wire name never appears
# literally and the `pub <ident>:` declarations are what to check; PAYLOAD fields
# carry explicit `rename = "…"` attrs; two payload fields are un-renamed idents.
# Transcript vocabulary decode_grok_line reads from the xAI SessionUpdate enum:
# variant IDENTS, since the snake_case tags derive via rename_all and the wire
# string never appears literally.
# The active_sessions.json registry struct grok_ids_from_registry parses (no
# rename_all — field idents ARE the wire names). A rename silently degrades the
# whole liveness ladder to mtime gating.

# omp is TRANSCRIPT-ONLY, and its depended names are split across the upstream
# files that define them. ONE-DIRECTIONAL like copilot: only a name WE DEPEND ON
# vanishing is breaking (the transcript still flows but decodes to nothing).
# The clean-teardown marker both the session-ended checker and the SessionEnd
# decode key on.
# Message-level names (roles + tool-call block shape) live in the pi-ai LLM types:
# quoted TS literals for the roles/block type, property keys for the fields.
# The ask tool's NAME is STATE-bearing — decode_omp_line maps an assistant `ask`
# block to Waiting — and the first question's text feeds the Waiting reason.
# `arguments.i` (the intent fallback) is harness-wide, not defined in ask.ts, and
# its loss only degrades the label, so it is deliberately unwatched.
# `omp::resolve_omp_sessions_dir` MIRRORS `DirResolver`. ONE-DIRECTIONAL: a
# depended env var VANISHING means we watch a sessions dir omp no longer writes
# to — an empty office and no error, the #880 fail-silent class.
# The SHAPES (Node-join binding, the agent/ flatten, the charset) are behaviour
# no name sweep can see — pinned by the omp axis-matrix unit tests.
# The `.env` OVERLAY that can move that same sessions dir. It is the ORDERING
# that is load-bearing: those files reach `process.env` only AFTER dirs.ts froze
# its resolver, so the post-load `refreshDirsFromEnv()` is what lets them move
# the sessions dir at all — lose it and OUR overlay becomes the divergence,
# honoring a file omp stopped reading. The value is the Rust half mirroring it.
# Split by ROLE, because the two halves send a maintainer to different code and
# a shared message would name the wrong requirement for one of them.
# `parseEnvFile` itself is the ANCHOR, so its rename lands as a blind probe
# rather than a rename line.
#
# The LOCATE-and-ORDER half: which dirs the files come from, and the rebuild
# that lets them reach the sessions dir at all.
# The line-PARSE half: what one `.env` line means once the file is found.
# `.env` is the filename we look for under each of omp's dirs; `OMP_` is the
# alias prefix that makes an `OMP_CODING_AGENT_DIR` reach the resolver as
# `PI_CODING_AGENT_DIR` (its `PI_` twin is built in a template literal, so only
# this half is quoted in the source and checkable as a literal).


class Anchor(typing.NamedTuple):
    """The declaration that OWNS the names we check a fetched document for."""

    pattern: str
    owns: str


# Absence is only evidence of an upstream RENAME if the document still contains
# the declaration that OWNS the name; drop that premise and a stale pin reads as
# mass drift (#793 reported three working env vars as renamed, because a moved
# module left a `pub use` facade that fetched 200 and greps empty).
#
# Choosing one, in descending strength — take the strongest available, because
# THIS comment is what picks the next anchor:
#   1. The DECLARATION that owns the checked names, so an upstream move takes
#      both and the sweep cannot run against a document missing them.
#   2. Failing that, a declaration co-located with them in the same file — this
#      proves file IDENTITY, which is weaker: "declaration X moved out while Y
#      stayed" satisfies the anchor and still reports phantom renames. Rows
#      marked `identity` below are that weaker grade; they are not upgradeable
#      without a parser, and a docs PAGE can only ever be this.
#   3. Never one of the checked names itself — that is circular and makes the
#      check vacuous (a rename would take the anchor too, so it could never fire).
# The three JSON Schemas are parsed STRUCTURALLY (`$defs`/`definitions` walked by
# `upstream_acp_session_update_tags` / `upstream_copilot_*`), so a text anchor
# would add nothing a failed parse does not already say. Every OTHER swept
# document is prose and must declare one — `every_swept_url_declares_an_anchor`
# is what stops a new sweep quietly skipping the #793 gate.
UNANCHORED_BY_DESIGN: frozenset[str] = frozenset(
    {ACP_V1_SCHEMA_URL, ACP_V1_SCHEMA_UNSTABLE_URL, COPILOT_SCHEMA_URL}
)

ANCHORS: dict[str, Anchor] = {
    # owner-grade: each anchor is the declaration the checked names live inside.
    # `_hermes_home_from_env` is the whole resolution we mirror (it reads
    # HERMES_HOME and delegates to the platform default), so it owns both names.
    # NOT `SessionNotification` (the obvious pick): it sits earlier in the file and
    # does not own the variants, so moving the enum out would leave it satisfied
    # while every variant read as renamed.
    # The const IDENT owns the checked VALUE `"session_exit"`; a value rename
    # keeps the identifier, so the anchor holds and the check still fires.
    # Owns the agentDir + XDG resolution; the profile / config-dir-name helpers
    # are its collaborators in the same file.
    # identity-grade: co-located, not owning. A union head or page title.
    CURSOR_HOOKS_URL: Anchor(r"hook_event_name", "the hook-event payload docs"),
    KIMI_HOOKS_URL: Anchor(r"hook_event_name", "the hook-event payload docs"),
    CC_TOOLS_URL: Anchor(r"(?m)^# Tools reference", "the tools-reference page"),
    CC_HOOKS_URL: Anchor(r"(?m)^# Hooks reference", "the hooks-reference page"),
}


# Documents where a PARSER is the identity proof instead. Written down so the
# selftest can assert this set equals the live `try_fetch` call sites — otherwise
# the next unanchored sweep just uses that spelling to escape the gate.


@dataclasses.dataclass
class Report:
    """One bucket per DISPOSITION, because each calls for a different action:

    `breaking` = verified upstream change, fix the decoder; `review` = a new
    surface to adopt or ignore; `blind` = probe health, repin and verify by hand;
    `errors` = transient. Collapsing `blind` into `breaking` is what made #793
    report five phantom renames. File through `add_*` only — pinned by the
    selftest.
    """

    breaking: list[str] = dataclasses.field(default_factory=list)
    review: list[str] = dataclasses.field(default_factory=list)
    blind: list[str] = dataclasses.field(default_factory=list)
    errors: list[str] = dataclasses.field(default_factory=list)

    def add_breaking(self, line: str) -> None:
        self.breaking.append(line)

    def add_review(self, line: str) -> None:
        self.review.append(line)

    def add_error(self, line: str) -> None:
        self.errors.append(line)

    def add_blind(
        self, what: str, where: str, consequence: str, *, our_source: bool = False
    ) -> None:
        """A lookup missed. Composed here so the disclaimer always ships with it.

        `our_source=True` when the unreadable thing is OURS — the default wording
        blames upstream, which nothing verified.
        """
        if our_source:
            cause = "Our own parser or constant is stale; nothing upstream was consulted."
            action = "Fix the script — this says nothing about upstream."
        else:
            cause = (
                "Upstream may have moved or reshaped it, or our pin/parser may be "
                "stale; this is NOT evidence that upstream changed."
            )
            action = (
                "Re-verify upstream by hand, then repin — do NOT change a decoder "
                "on this alone."
            )
        self.blind.append(
            f"could not verify {what} at {where} — {cause} {consequence} {action}"
        )

    def title(self) -> str:
        """The report's H1, which IS the GitHub issue title.

        upstream-drift.yml reads it back off the rendered report rather than
        keeping a second, unpinned copy of these strings. Ordered by disposition
        so the issue list itself carries the strongest finding.
        """
        if self.breaking:
            return "Upstream CLI wire-format drift detected"
        if self.review:
            return "New upstream events to review"
        if self.blind:
            return "Upstream drift watch could not verify — repin needed"
        return "Upstream wire-format watch: no drift"

    def render(self) -> str:
        out = [f"# {self.title()}", ""]
        if self.breaking:
            out.append("## ⛔ Verified upstream change — decoder will silently drop events")
            out.append("")
            out.append(
                "Each line was read off the upstream surface that OWNS the name: the "
                "declaration is present and the name is gone. Fix the decoder."
            )
            out.append("")
            out += [f"- {b}" for b in self.breaking]
            out.append("")
        if self.review:
            out.append("## 🔎 New upstream events to review")
            out += [f"- {r}" for r in self.review]
            out.append("")
        if self.blind:
            out.append("## 🩺 Probe could NOT verify — this is not evidence of upstream change")
            out.append("")
            out.append(
                "A lookup missed, so all the watcher knows is that **its own probe "
                "failed**. A stale pin, a moved declaration, or a refactor that left a "
                "re-export facade at the old path all land here, and every check "
                "riding the affected surface was SKIPPED rather than reported as "
                "drift. **Verify upstream by hand and repin — do NOT change a decoder "
                "on these lines alone** (#793 did, against three working env vars)."
            )
            out.append("")
            out += [f"- {b}" for b in self.blind]
            out.append("")
        if self.errors:
            out.append("## ⚠️ Could not verify (transient network/HTTP — not drift)")
            out += [f"- {e}" for e in self.errors]
            out.append("")
        if not (self.breaking or self.review or self.blind or self.errors):
            out.append("✅ No drift. Every name we depend on is present upstream.")
        return "\n".join(out)

    def exit_code(self) -> int:
        """0 no findings / 1 actionable / 2 could not check (transient).

        `blind` is actionable — the watch is DARK for that source until someone
        repins — so it exits 1 even though the report no longer calls it drift.
        Drop it from this condition and a report saying the watch is dark exits 0:
        both `exit == '1'` steps in upstream-drift.yml skip and the weekly run
        goes green (#454's fail-open).
        """
        if self.breaking or self.review or self.blind:
            return 1
        if self.errors:
            return 2
        return 0


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "pixtuoid-drift-watch"})
    with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310 (trusted hosts)
        return resp.read().decode("utf-8", "replace")


def try_fetch(url: str, label: str, report: Report) -> str | None:
    """Fetch `url`, classifying failures so a PERMANENT upstream move is loud.

    A `PERMANENT_HTTP_STATUS` means our pin is wrong/gone → `blind` (a fact about
    OUR pin, not about upstream's wire format); everything else → `errors`.
    Returns None on any failure, and the caller skips that source's checks.
    """
    try:
        return fetch(url)
    except urllib.error.HTTPError as e:
        if e.code in PERMANENT_HTTP_STATUS:
            report.add_blind(
                f"{label}",
                f"{url} (HTTP {e.code})",
                "Every check for this source was SKIPPED.",
            )
        else:
            report.add_error(f"{label}: transient HTTP {e.code} at {url}: {e}")
        return None
    except FETCH_ERRORS as e:
        report.add_error(f"{label}: fetch failed (transient?): {e}")
        return None


def fetch_anchored(url: str, label: str, report: Report) -> str | None:
    """`try_fetch` plus the identity proof required before sweeping a document.

    Returns the body only when the document still contains its `ANCHORS` entry.
    A missing anchor means the fetch succeeded but landed on the wrong content
    (a re-export facade, a restructured page), so every presence check that would
    have run is SKIPPED and reported as probe health instead of drift.

    An undeclared URL is reported, never swept — deliberately not raised:
    `run_checks` routes exceptions to the TRANSIENT bucket, so a bare `KeyError`
    would degrade "someone added an unproven sweep" into a warning on a green run.
    """
    anchor = ANCHORS.get(url)
    if anchor is None:
        report.add_blind(
            f"{label}: no ANCHORS entry declares what proves this document's identity",
            url,
            "It was NOT swept — an unproven document cannot distinguish an "
            "upstream rename from a stale pin. Add its anchor to ANCHORS "
            "(and a sample to the selftest's ANCHOR_SAMPLES).",
        )
        return None
    text = try_fetch(url, label, report)
    if text is None:
        return None
    if not re.search(anchor.pattern, text):
        report.add_blind(
            f"{label}: the document no longer contains {anchor.owns}",
            url,
            "It still fetches, so the probe landed on the wrong content — "
            "most likely a stale pin (a moved declaration, or a re-export "
            "facade left at the old path) rather than an upstream rename. "
            "Every presence check riding this document was SKIPPED, NOT "
            "reported as drift.",
        )
        return None
    return text
















def upstream_acp_session_update_tags(text: str) -> set[str] | None:
    """The ACP `SessionUpdate` discriminator tags from a v1 JSON schema. Returns
    None if the schema won't parse or the union is absent → the caller files probe
    health and SKIPS the check."""
    try:
        root = json.loads(text)
    except json.JSONDecodeError:
        return None
    defs = root.get("$defs") or root.get("definitions") or {}
    if not isinstance(defs, dict):
        return None
    su = defs.get("SessionUpdate")
    members = su.get("oneOf") or su.get("anyOf") if isinstance(su, dict) else None
    if not isinstance(members, list):
        return None
    tags: set[str] = set()
    for member in members:
        if not isinstance(member, dict):
            continue
        node = member
        ref = member.get("$ref", "")
        if ref:
            node = defs.get(ref.rsplit("/", 1)[-1], {})
        const = (
            node.get("properties", {}).get("sessionUpdate", {}).get("const")
            if isinstance(node, dict)
            else None
        )
        if isinstance(const, str):
            tags.add(const)
    return tags or None
















def _snake_case(camel: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", camel).lower()








def codex_function_call_fields(text: str) -> set[str] | None:
    """The field idents of the INLINE `ResponseItem::FunctionCall { … }` variant.

    Returns None if it isn't an inline struct — a GRACEFUL SKIP, not an alarm: a
    tuple-variant refactor serializes the SAME JSON, so the decoder still works
    and only this bonus check goes quiet."""
    m = re.search(r"FunctionCall\s*\{([^}]*)\}", text)
    if not m:
        return None
    return set(re.findall(r"\b([a-z_][a-z0-9_]*)\s*:", m.group(1)))




def upstream_cc_hook_events(text: str) -> set[str] | None:
    """The canonical event list is the "| Event | When it fires |" summary table —
    parse only its rows, since other tables repeat names with different columns."""
    m = re.search(r"^\|\s*Event\s*\|[^\n]*\n\|[\s:|-]*\n((?:\|[^\n]*\n)+)", text, re.M)
    if not m:
        return None
    return set(re.findall(r"^\|\s*`(\w+)`\s*\|", m.group(1), re.M)) or None































def _copilot_type_const(sch: object) -> str | None:
    """The wire `type` string a copilot schema definition pins — `properties.type`
    as a `const` or a single-element `enum`. Shared by the event and namespace
    readers so the two can't drift on how a type-tag is expressed."""
    if not isinstance(sch, dict):
        return None
    t = sch.get("properties", {}).get("type")
    if not isinstance(t, dict):
        return None
    c = t.get("const")
    if c is None:
        enum = t.get("enum")
        if isinstance(enum, list) and len(enum) == 1:
            c = enum[0]
    return c if isinstance(c, str) else None


def upstream_copilot_events(text: str) -> set[str] | None:
    """The per-event `type` consts from the @github/copilot session-events JSON
    schema."""
    try:
        defs = json.loads(text).get("definitions", {})
    except (json.JSONDecodeError, AttributeError):
        return None
    consts = {c for sch in defs.values() if (c := _copilot_type_const(sch))}
    return consts or None


def upstream_copilot_namespaces(text: str) -> set[str] | None:
    """The NAMESPACE families of the copilot `SessionEvent` union. Scoped to the
    anyOf union ON PURPOSE: a naive walk of ALL `definitions` also pulls in
    nested-content type-tags (`audio`/`text`/`image`/…) that share the
    `type.const` shape but are never a top-level envelope `type`, inflating the
    set with phantom families. Returns None → the caller files probe health and
    SKIPS every Copilot check."""
    try:
        defs = json.loads(text).get("definitions", {})
    except (json.JSONDecodeError, AttributeError):
        return None
    anyof = defs.get("SessionEvent", {}).get("anyOf") if isinstance(defs, dict) else None
    if not isinstance(anyof, list):
        return None
    namespaces: set[str] = set()
    for member in anyof:
        ref = member.get("$ref", "") if isinstance(member, dict) else ""
        name = ref.rsplit("/", 1)[-1] if ref else ""
        c = _copilot_type_const(defs.get(name))
        if c:
            namespaces.add(c.split(".", 1)[0])
    return namespaces or None


def upstream_copilot_field_names(text: str) -> set[str] | None:
    """The union of every `properties` key at ANY depth — envelope fields AND the
    nested `data.properties` ones. Used one-directional: a field the decoder READS
    that is absent from the whole schema is a rename."""
    try:
        root = json.loads(text)
    except json.JSONDecodeError:
        return None
    names: set[str] = set()

    def walk(node: object) -> None:
        if isinstance(node, dict):
            props = node.get("properties")
            if isinstance(props, dict):
                names.update(k for k in props if isinstance(k, str))
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(root)
    return names or None




def cc_doc_marker_findings(hooks_doc: str) -> list[str]:
    # Depended markers alarm on VANISH, surface markers on APPEARANCE. Not named
    # `review`: the selftest bans a bucket-named local outside `Report`.
    findings: list[str] = []
    for marker, what in sorted(CC_DEPENDED_DOC_MARKERS.items()):
        if marker not in hooks_doc:
            findings.append(
                f"CC hooks.md no longer mentions `{marker}` — {what} may have "
                f"moved/renamed; re-verify the burn-tier hook decode."
            )
    for marker, what in sorted(CC_LIFECYCLE_SURFACE_MARKERS.items()):
        if marker in hooks_doc:
            findings.append(
                f"CC hooks doc now mentions `{marker}` — {what} may have "
                f"landed upstream. Adopt it (a durable end signal for the "
                f"JSONL transport / the liveness-probe registry) and "
                f"update this watch."
            )
    return findings


@dataclasses.dataclass
class OurNames:
    """What WE depend on, read from our OWN source — one field per READER.

    `None` means that reader failed; every consumer guards on `is not None`, so a
    stale parser darkens exactly what it fed and nothing else."""

    codex: set[str] | None = None
    codex_rollout: tuple[set[str], set[str], set[str]] | None = None
    acp_decoded_tags: set[str] | None = None
    cc: set[str] | None = None
    dispatch_names: set[str] | None = None
    reasonix: set[str] | None = None
    codewhale: set[str] | None = None
    opencode: set[str] | None = None
    copilot: set[str] | None = None
    omp: set[str] | None = None
    cursor: set[str] | None = None
    openclaw: set[str] | None = None
    hermes: set[str] | None = None
    grok: set[str] | None = None
    grok_xai_method: str | None = None
    kimi: set[str] | None = None


# (OurNames field, reader, the surface it reads — the wording of its probe-health
# line). A table because each row needs its OWN `try`; rows hold function OBJECTS
# captured at import, so a test injecting a stale reader must replace the ROW, not
# the module attribute.


# A parse smaller than this is not believed, so BOTH drift directions are SKIPPED
# for that source and the run files probe health instead. Each number is a
# MEASUREMENT of the upstream document taken when the row was written; an absent
# source claims only the derived minimum (what we already handle). #929's false
# "fix the decoder" against `pre_approval_request` came from a partial document
# that cleared a bare non-emptiness check.
# The document each floor is measured against — named in the probe-health line so
# a maintainer knows which pin to re-check.
PARSE_SOURCES: dict[str, str] = {
    "cc": "the hook-event summary table in hooks.md",
}


def parse_is_believable(source: str, upstream: set[str], ours: OurNames, report: Report) -> bool:
    """The floor, asked BEFORE EITHER direction — files probe health and returns
    False when the parse is too small to believe.

    It used to gate only the review half. The VANISH half — which files ⛔ "fix
    the decoder", the highest severity this report has — was gated on bare
    non-emptiness, so a reader returning 12 of 37 names could file five ⛔ against
    working decoders and only then be stopped. That is not hypothetical: #929's
    false ⛔ against `pre_approval_request` came from exactly a partial document.
    """
    # The key IS the `OurNames` field — pinned by the selftest's census.
    handled = getattr(ours, source) or set()
    # A reader that finds fewer names than we already handle is broken, or — where
    # the two directions read different populations (cursor's anchor index, kimi's
    # Event Reference table, against a vanish half that searches raw prose) — it is
    # degraded. Probe health is the right answer to both.
    floor = len(handled)
    if len(upstream) < floor:
        report.add_blind(
            f"the {source} name set upstream actually offers",
            PARSE_SOURCES[source],
            f"the reader returned {len(upstream)} names (floor {floor}), so the "
            f"vanish check was SKIPPED for {source}.",
        )
        return False
    return True


# Each row is one OurNames field and where the emitting crate puts it. The
# fragments are GENERATED by a test in the crate that owns the names
# (`src/drift_surface.rs` in each), so a rename is a test failure THERE rather
# than a parser here quietly returning a smaller set.
SURFACE_ROWS: tuple[tuple[str, str, str, str], ...] = (
    ("codex", CORE_BIN_FRAGMENT, "registered", "codex"),
    ("cc", CORE_BIN_FRAGMENT, "registered", "claude-code"),
    ("reasonix", CORE_BIN_FRAGMENT, "registered", "reasonix"),
    ("codewhale", CORE_BIN_FRAGMENT, "registered", "codewhale"),
    ("cursor", CORE_BIN_FRAGMENT, "registered", "cursor"),
    ("openclaw", CORE_BIN_FRAGMENT, "registered", "openclaw"),
    ("hermes", CORE_BIN_FRAGMENT, "registered", "hermes"),
    ("grok", CORE_BIN_FRAGMENT, "registered", "grok"),
    ("kimi", CORE_BIN_FRAGMENT, "registered", "kimi"),
    ("acp_decoded_tags", CORE_LIB_FRAGMENT, "decoded", "acp.session_update_tags"),
    ("copilot", CORE_LIB_FRAGMENT, "decoded", "copilot.kinds"),
    ("omp", CORE_LIB_FRAGMENT, "decoded", "omp.entry_types"),
    ("opencode", CORE_LIB_FRAGMENT, "decoded", "opencode.hook_events"),
    ("dispatch_names", CORE_LIB_FRAGMENT, "decoded", "decoder.dispatch_names"),
)


def load_fragment(rel: str) -> dict:
    """One emitted drift-surface half. Raises so the caller can file probe health
    naming the fragment — a missing file is OUR build being wrong, never evidence
    about upstream."""
    return json.loads((REPO / rel).read_text())


def read_our_names(report: Report) -> OurNames:
    """Read every depended name from the EMITTED drift surface.

    Per-KEY isolation, as the 16 hand-written parsers had per-reader: a fragment
    that loads but lacks one row darkens exactly that field. A fragment that does
    not load at all darkens every field it feeds, which is honest — the file is
    generated as a whole, so it is never partially stale.

    A gap here means the MONITOR is broken: loud probe health (exit 1), never
    transient."""
    ours = OurNames()
    frags: dict[str, dict] = {}
    for rel in (CORE_LIB_FRAGMENT, CORE_BIN_FRAGMENT):
        try:
            frags[rel] = load_fragment(rel)
        except Exception as e:  # noqa: BLE001
            report.add_blind(
                f"what WE depend on, reading {rel} ({e})",
                f"the drift surface emitted by {rel.rsplit('/', 1)[0]}",
                "That fragment is missing or unparseable, so every check it feeds "
                "was SKIPPED. Regenerate with `UPDATE_DRIFT_SURFACE=1 just test`.",
                our_source=True,
            )
    for field, rel, group, key in SURFACE_ROWS:
        frag = frags.get(rel)
        if frag is None:
            continue
        got = frag.get(group, {}).get(key)
        if not got:
            report.add_blind(
                f"what WE depend on for `{field}`, reading {group}.{key} in {rel}",
                "the emitted drift surface",
                f"That row is absent or empty, so the `{field}` upstream checks "
                f"were SKIPPED. Every OTHER source still ran.",
                our_source=True,
            )
            continue
        setattr(ours, field, set(got))
    # The one non-set field: codex compares three sets that ride one parse.
    lib = frags.get(CORE_LIB_FRAGMENT)
    if lib is not None:
        d = lib.get("decoded", {})
        triple = (d.get("codex.event_msg"), d.get("codex.response_item"), d.get("codex.rollout_outers"))
        if all(triple):
            ours.codex_rollout = tuple(set(x) for x in triple)  # type: ignore[assignment]
        else:
            report.add_blind(
                "what WE depend on for `codex_rollout`, reading the codex rows",
                "the emitted drift surface",
                "A codex rollout row is absent or empty, so the rollout checks "
                "were SKIPPED. Every OTHER source still ran.",
                our_source=True,
            )
        method = lib.get("values", {}).get("grok.xai_session_update_method")
        if method:
            ours.grok_xai_method = method  # type: ignore[assignment]
        else:
            report.add_blind(
                "what WE depend on for `grok_xai_method`",
                "the emitted drift surface",
                "The xAI method value is absent, so that watch was SKIPPED.",
                our_source=True,
            )
    return ours


def run_checks(ours: OurNames, *, report: Report) -> None:
    """The upstream comparisons, filing what they find into `report`.

    Split from main() so an UNEXPECTED exception here can be routed to the
    transient bucket with the partial report intact — without it the interpreter
    exits 1 and the workflow files a junk drift-titled issue from an empty report.

    Every block guards on its own `ours.<field> is not None`, so one stale reader
    costs exactly what it fed. No `read_*` may be called from here: an inline read
    unwinds to that catch-all and is filed TRANSIENT — a warning on a green run —
    which is strictly worse than the probe-health line `read_our_names` files."""
    # protocol.rs holds BOTH the HookEventName enum and the EventMsg enum.





    # The ACP method `session/update` and the two `sessionUpdate` tags
    # `decode_session_update` turns into events. v1 only — grok does not speak v2.
    # xAI's OWN `_x.ai/session/update` is watched separately, off its declaration.
    up_acp: set[str] = set()
    acp_method_surface = False
    acp_method_declared = False
    acp_parsed = False
    for url, label in (
        (ACP_V1_SCHEMA_URL, "ACP v1 schema"),
        (ACP_V1_SCHEMA_UNSTABLE_URL, "ACP v1 unstable schema"),
    ):
        acp_text = try_fetch(url, label, report)
        if acp_text is None:
            continue
        tags = upstream_acp_session_update_tags(acp_text)
        if tags is None:
            report.add_blind(
                "the ACP `SessionUpdate` oneOf union",
                label,
                "The ACP decoded-tag watch was SKIPPED.",
            )
        else:
            up_acp |= tags
            acp_parsed = True
            # `"x-method"` is the surface that OWNS the method names, and it is a
            # generator-emitted vendor extension — a codegen change can move it
            # wholesale. Its PRESENCE is this check's anchor: absent, the probe
            # landed on a schema that no longer declares methods (probe health);
            # present without ours, the name is genuinely gone.
            acp_method_surface |= '"x-method"' in acp_text
            acp_method_declared |= '"session/update"' in acp_text
    if acp_parsed and not acp_method_surface:
        report.add_blind(
            "the ACP `x-method` declarations",
            "the ACP v1 schemas",
            "The ACP method watch was SKIPPED — the schema parses but declares no "
            "methods at all, so this is a restructure, NOT evidence of a rename.",
        )
    elif acp_parsed and not acp_method_declared:
        report.add_breaking(
            "the ACP method `session/update` is GONE from the ACP schema — renamed; "
            "`decode_grok_line` gates whether the tag is INTERPRETED, so every "
            "ACP-standard activity event is silently lost (`_ => Ok(vec![])`, no "
            "breadcrumb)."
        )
    if acp_parsed:
        for tag in sorted(ours.acp_decoded_tags or ()):
            if tag not in up_acp:
                report.add_breaking(
                    f"ACP v1 `sessionUpdate` tag `{tag}` (decoded in source/acp.rs) is "
                    f"GONE from the ACP schema — renamed; every ACP-speaking source "
                    f"loses that half of its activity decode."
                )

    if ours.copilot is not None:
        text = try_fetch(COPILOT_SCHEMA_URL, "Copilot schema", report)
        # The `SessionEvent` union is this document's ANCHOR: a parseable JSON is
        # NOT enough, one stray `properties` object reports every field renamed.
        up_ns = upstream_copilot_namespaces(text) if text is not None else None
        if text is not None and up_ns is None:
            report.add_blind(
                "the Copilot `SessionEvent` anyOf union",
                COPILOT_SCHEMA_URL,
                "EVERY Copilot check (event types, payload fields) was SKIPPED — "
                "an unproven schema cannot tell a rename from a restructure.",
            )
        if text is not None and up_ns is not None:
            upstream = upstream_copilot_events(text)
            if upstream is None:
                report.add_blind(
                    "any parseable `type` const in the Copilot session-events schema",
                    COPILOT_SCHEMA_URL,
                    "The Copilot event watch was SKIPPED.",
                )
            else:
                for ev in sorted(ours.copilot):
                    if ev not in upstream:
                        report.add_breaking(
                            f"Copilot event `{ev}` (decoded in source/copilot.rs) is GONE "
                            f"from the @github/copilot schema — likely renamed; the "
                            f"transcript still carries it but the decoder maps it to "
                            f"nothing (no sprite / no activity)."
                        )
            fields_up = upstream_copilot_field_names(text)
            if fields_up is None:
                report.add_blind(
                    "the Copilot schema `properties` keys",
                    COPILOT_SCHEMA_URL,
                    "The Copilot payload-field watch was SKIPPED.",
                )
            else:
                for field in sorted(COPILOT_PAYLOAD_FIELDS):
                    if field not in fields_up:
                        report.add_breaking(
                            f"Copilot field `{field}` (read by decode_copilot_line / "
                            f"extract_copilot_cwd) is GONE from the schema properties — "
                            f"renamed; the decoder reads None (wrong-register / no-link / "
                            f"no tool label / permission never gates)."
                        )


    if ours.cursor is not None:
        text = fetch_anchored(CURSOR_HOOKS_URL, "Cursor hooks doc", report)
        if text is not None:
            for ev in sorted(ours.cursor):
                # Word-boundary, not quote-anchored: the docs render the names
                # inline / in tables, never as quoted literals.
                if not re.search(rf"\b{re.escape(ev)}\b", text):
                    report.add_breaking(
                        f"Cursor hook `{ev}` (decoded in source/cursor.rs) is GONE from "
                        f"cursor.com/docs/hooks — likely renamed; the CLI still fires it but "
                        f"the decoder maps it to nothing (no sprite / no activity)."
                    )




    if ours.kimi is not None:
        text = fetch_anchored(KIMI_HOOKS_URL, "Kimi hooks doc", report)
        if text is not None:
            for ev in sorted(ours.kimi):
                # Word-boundary like the Cursor check: the doc renders each name
                # inline / in a summary table, never as a quoted literal.
                if not re.search(rf"\b{re.escape(ev)}\b", text):
                    report.add_breaking(
                        f"Kimi hook `{ev}` (registered in KIMI_EVENTS) is GONE from "
                        f"kimi-code docs/en/customization/hooks.md — likely renamed; "
                        f"Kimi still fires it but the decoder maps it to nothing "
                        f"(no sprite / no activity)."
                    )

    if ours.dispatch_names is not None:
        tools = fetch_anchored(CC_TOOLS_URL, "CC tools-reference", report)
        if tools is not None:
            # At least one name we'd detect by-name must still be the documented
            # dispatch tool. (Losing a legacy name like `Task` is fine.)
            present = [n for n in ours.dispatch_names if re.search(rf"`{re.escape(n)}`", tools)]
            if not present:
                report.add_breaking(
                    f"None of our known dispatch tool names {sorted(ours.dispatch_names)} "
                    f"appear in CC tools-reference — the subagent tool was likely "
                    f"renamed again. Update make_tool_detail's known names. (Semantic "
                    f"subagent_type detection still works, but the name fallback is "
                    f"stale.)"
                )

    # The lifecycle-marker scan is unconditional: there is nothing to read from
    # our source first, since we depend on those surfaces' ABSENCE.
    hooks_doc = fetch_anchored(CC_HOOKS_URL, "CC hooks doc", report)
    if hooks_doc is not None:
        if ours.cc is not None:
            upstream = upstream_cc_hook_events(hooks_doc)
            if upstream is None:
                report.add_blind(
                    "the CC hook-event summary table",
                    "hooks.md",
                    "The CC event watch was SKIPPED.",
                )
            elif parse_is_believable("cc", upstream, ours, report):
                for ev in sorted(ours.cc):
                    if ev not in upstream:
                        report.add_breaking(
                            f"CC hook `{ev}` (registered in install/claude.rs "
                            f"EVENTS) is GONE from hooks.md — likely renamed; "
                            f"the decoder will silently drop it."
                        )
        for finding in cc_doc_marker_findings(hooks_doc):
            report.add_review(finding)


def main() -> int:
    report = Report()

    ours = read_our_names(report)

    try:
        run_checks(ours, report=report)
    except Exception as e:  # noqa: BLE001
        traceback.print_exc()
        report.add_error(
            f"unexpected error during the upstream checks "
            f"({type(e).__name__}: {e}) — treating as transient; the report "
            f"covers only the checks that completed (traceback on stderr)"
        )

    print(report.render())
    return report.exit_code()


if __name__ == "__main__":
    sys.exit(main())
