#!/usr/bin/env python3
"""Pixel-exact comparison of a rendered snapshot against a checked-in reference.

CI gate: the smoke job renders deterministic frames (see `just gen-check`)
and fails if they differ from docs/images/reference-*.png. The references are
regenerated by scripts/gen-media.py (`just gen`) — a PR that
intentionally changes the office's look must commit the regenerated references
in the same change.

Exit codes: 0 = identical, 1 = images differ (diff overlay written),
2 = could not compare (usage / missing / unreadable / size mismatch).

NOTE: compare in RGB, never RGBA — ImageChops.difference of two opaque RGBA
images has an all-zero alpha band, and Pillow >= 10's getbbox() defaults to
alpha_only=True, which would make ANY two same-size images compare equal.
"""

import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageChops, UnidentifiedImageError


def compare_images(ref_path, cand_path, diff_path, threshold_percent=0.0):
    """Returns an exit code (see module docstring)."""
    ref_path = Path(ref_path)
    cand_path = Path(cand_path)
    diff_path = Path(diff_path)

    try:
        ref = Image.open(ref_path).convert("RGB")
    except (OSError, UnidentifiedImageError) as e:
        print(f"ERROR: cannot read reference image {ref_path}: {e}")
        return 2
    try:
        cand = Image.open(cand_path).convert("RGB")
    except (OSError, UnidentifiedImageError) as e:
        print(f"ERROR: cannot read candidate image {cand_path}: {e}")
        return 2

    if ref.size != cand.size:
        print(f"ERROR: Image sizes differ. Reference: {ref.size}, Candidate: {cand.size}")
        return 2

    diff = ImageChops.difference(ref, cand)
    if diff.getbbox() is None:
        print(f"SUCCESS: {cand_path.name} is pixel-identical to {ref_path.name}.")
        return 0

    # Generate a visual difference overlay highlighting mismatches in red.
    diff_data = diff.load()
    cand_data = cand.load()

    w, h = ref.size
    mismatched = 0

    out = Image.new("RGB", (w, h))
    out_data = out.load()

    for y in range(h):
        for x in range(w):
            if diff_data[x, y] != (0, 0, 0):
                mismatched += 1
                out_data[x, y] = (255, 0, 0)  # highlight mismatched pixels in red
            else:
                # Dim the matching background so the red overlay pops.
                c_pix = cand_data[x, y]
                out_data[x, y] = (c_pix[0] // 2, c_pix[1] // 2, c_pix[2] // 2)

    total_pixels = w * h
    percent = (mismatched / total_pixels) * 100.0
    print(f"MISMATCH: {mismatched} / {total_pixels} pixels differ ({percent:.4f}%)")

    diff_path.parent.mkdir(parents=True, exist_ok=True)
    out.save(diff_path)
    print(f"Difference highlight image saved to: {diff_path}")

    # The render is byte-deterministic, so the default tolerance is zero; a
    # nonzero threshold must be an explicit, visible choice at the call site.
    if percent > threshold_percent:
        print(f"ERROR: Mismatch {percent:.4f}% exceeds the allowed threshold of {threshold_percent}%.")
        return 1

    print("SUCCESS: Mismatch is within the acceptable threshold.")
    return 0


def _selftest():
    """Assert the comparator can actually FAIL. Returns an exit code.

    Two required gates (`gen-check`, smoke) ride on this predicate, so a
    silently-always-green comparator would report success for any render. The
    RGBA case below is the specific always-green mode the module docstring
    warns about: drop the `.convert("RGB")` and ImageChops.difference leaves an
    all-zero alpha band that Pillow >= 10's alpha_only=True getbbox() reads as
    "no difference" — every case here still passes EXCEPT that one.
    """
    checks = []

    def check(name, got, want):
        checks.append((name, got, want))

    black = (0, 0, 0)
    white = (255, 255, 255)

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        diff_out = td / "diff.png"

        def write(name, mode, color, size=(8, 8)):
            p = td / name
            Image.new(mode, size, color).save(p)
            return p

        # THE anti-rot check: opaque RGBA, differing only in colour. Without the
        # RGB conversion this returns 0 and the whole gate is decorative.
        rgba_a = write("rgba_a.png", "RGBA", black + (255,))
        rgba_b = write("rgba_b.png", "RGBA", white + (255,))
        check("differing RGBA images must FAIL", compare_images(rgba_a, rgba_b, diff_out), 1)

        rgb_a = write("rgb_a.png", "RGB", black)
        rgb_b = write("rgb_b.png", "RGB", white)
        check("differing RGB images must FAIL", compare_images(rgb_a, rgb_b, diff_out), 1)

        check("identical images must PASS", compare_images(rgb_a, rgb_a, diff_out), 0)

        bigger = write("bigger.png", "RGB", black, size=(16, 16))
        check("size mismatch must ERROR", compare_images(rgb_a, bigger, diff_out), 2)

        check("missing file must ERROR", compare_images(td / "nope.png", rgb_a, diff_out), 2)

        # A threshold must gate on the measured percentage, not swallow the diff:
        # one differing pixel in 100 is 1%, so 0.5% fails and 2% passes.
        spotted = Image.new("RGB", (10, 10), black)
        spotted.putpixel((0, 0), white)
        spot = td / "spot.png"
        spotted.save(spot)
        flat = write("flat.png", "RGB", black, size=(10, 10))
        check("1% diff under a 0.5% threshold must FAIL", compare_images(flat, spot, diff_out, 0.5), 1)
        check("1% diff under a 2% threshold must PASS", compare_images(flat, spot, diff_out, 2.0), 0)
        # ON the boundary, so `>` vs `>=` is observable. Both cases above sit off
        # it, which let a flipped operator survive; a threshold is a policy and
        # its inclusivity is the part worth pinning.
        check("1% diff exactly AT a 1% threshold must PASS", compare_images(flat, spot, diff_out, 1.0), 0)

        # The consumers do not import this module — gen-media.py and
        # gen-pix-icons.py subprocess it. Exercise that path too, or argv
        # handling and the exit-code mapping stay untested however many
        # in-process checks pass.
        argv = [sys.executable, str(Path(__file__).resolve())]
        cli_ok = subprocess.run([*argv, str(rgb_a), str(rgb_a), str(diff_out)], capture_output=True)
        check("CLI: identical images exit 0", cli_ok.returncode, 0)
        cli_bad = subprocess.run([*argv, str(rgb_a), str(rgb_b), str(diff_out)], capture_output=True)
        check("CLI: differing images exit 1", cli_bad.returncode, 1)
        cli_usage = subprocess.run([*argv, str(rgb_a)], capture_output=True)
        check("CLI: wrong arity exits 2", cli_usage.returncode, 2)

    failed = [(n, got, want) for n, got, want in checks if got != want]
    for name, got, want in failed:
        print(f"SELFTEST FAIL: {name} — got exit {got}, want {want}", file=sys.stderr)
    if failed:
        print(f"compare-screenshots selftest: {len(failed)}/{len(checks)} checks FAILED", file=sys.stderr)
        return 1
    print(f"compare-screenshots selftest: all {len(checks)} checks passed", file=sys.stderr)
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv[1:]:
        sys.exit(_selftest())

    if len(sys.argv) not in (4, 5):
        print("Usage: compare-screenshots.py <reference> <candidate> <diff_out> [threshold_percent]")
        print("       compare-screenshots.py --selftest")
        sys.exit(2)

    threshold = float(sys.argv[4]) if len(sys.argv) == 5 else 0.0
    sys.exit(compare_images(sys.argv[1], sys.argv[2], sys.argv[3], threshold))
