//! Effects that ride on a character, a pet or a fixture, painted with it in
//! z-order in their [look](crate::effects::look), and a screen's own.

use pixtuoid_core::sprite::{Rgb, RgbBuffer};

use super::palette::{WHITE, blend_pixel};
use crate::effects::Effect;
use crate::effects::look::{Inks, plot_effect, scanline_color};
use crate::layout::SCREEN_GLASS_COLS;
use crate::theme::Theme;

/// Standby tint on a BACK-TURNED desk's glass — a grid of black rectangles reads as "everyone went home".
pub(super) fn paint_screen_idle(
    buf: &mut RgbBuffer,
    desk_x: u16,
    sprite_top: u16,
    tint: Rgb,
    strength: f32,
) {
    if strength <= 0.0 {
        return;
    }
    for dx in SCREEN_GLASS_COLS {
        for dy in SCREEN_GLASS_ROWS {
            blend_pixel(buf, desk_x + dx, sprite_top + dy, tint, strength);
        }
    }
}

/// Casing rows offset from the sprite TOP; lighting only the lower one leaves a black bar capping the glow.
const SCREEN_CASING_ROWS: std::ops::RangeInclusive<u16> = 0..=1;
const SCREEN_GLASS_ROWS: std::ops::RangeInclusive<u16> = 2..=3;
const SCREEN_CHIN_ROW: u16 = 4;

/// `sprite_top` is the monitor's first frame row, NOT `desk.y` — a raised monitor sits rows higher.
pub(super) fn paint_screen_glow(
    buf: &mut RgbBuffer,
    desk_x: u16,
    sprite_top: u16,
    scanline: u16,
    tint: Rgb,
    theme: &Theme,
) {
    // Untinted, the theme's cool `monitor_frame_lit` read as a metal plate capping the glow.
    const CASING_TINT: f32 = 0.35;
    let frame_lit = theme.effects.monitor_frame_lit.mix(tint, CASING_TINT);
    let glow = tint;
    let glow_bright = tint.mix(WHITE, 0.4);
    let line_color = scanline_color(tint);
    let put = |buf: &mut RgbBuffer, dx: u16, dy: u16, c: Rgb| {
        buf.put_checked(desk_x + dx, sprite_top + dy, c);
    };
    // The casing frames the glass, one column proud of it on each side.
    let casing_cols = SCREEN_GLASS_COLS.start() - 1..=SCREEN_GLASS_COLS.end() + 1;
    for dy in SCREEN_CASING_ROWS {
        for dx in casing_cols.clone() {
            put(buf, dx, dy, frame_lit);
        }
    }
    let (glass_upper, glass_lower) = (*SCREEN_GLASS_ROWS.start(), *SCREEN_GLASS_ROWS.end());
    for dx in SCREEN_GLASS_COLS {
        put(buf, dx, glass_upper, glow_bright);
        put(buf, dx, glass_lower, glow);
    }
    for dx in SCREEN_GLASS_COLS {
        put(buf, dx, SCREEN_CHIN_ROW, frame_lit);
    }
    let scan_col = SCREEN_GLASS_COLS.start() + scanline;
    for dy in SCREEN_GLASS_ROWS {
        put(buf, scan_col, dy, line_color);
    }
}

/// Paint `e` in its look.
pub(super) fn paint_effect(buf: &mut RgbBuffer, e: &Effect, theme: &Theme) {
    plot_effect(e, &Inks::of(theme), &mut |x, y, c, alpha| {
        if alpha >= 1.0 {
            buf.put_checked(x, y, c);
        } else {
            blend_pixel(buf, x, y, c, alpha);
        }
    });
}

/// [`paint_effect`] each of `effects`, in order.
pub(super) fn paint_effects<'e>(
    buf: &mut RgbBuffer,
    effects: impl IntoIterator<Item = &'e Effect>,
    theme: &Theme,
) {
    for e in effects {
        paint_effect(buf, e, theme);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::Point;
    use std::time::{Duration, SystemTime};

    fn theme() -> &'static Theme {
        crate::theme::theme_by_name("normal").expect("normal theme")
    }

    /// The glow is placed by `SCREEN_*`; the art is generated by
    /// scripts/gen-art.py. This pins the pair on the bundled back-turned desk,
    /// the one whose screen a sitter works at: glass under every glass pixel
    /// the glow paints, and an opaque, non-glass casing and chin around it.
    #[test]
    fn the_glow_lands_on_the_desk_arts_monitor() {
        use crate::pack::{SCREEN_GLASS_KEY, SCREEN_TEXT_KEY};
        let pack = crate::pack::test_office();
        let art = pack
            .piece(pixtuoid_core::sprite::format::Piece::DeskNorth)
            .first();
        let screen: Vec<Rgb> = [SCREEN_GLASS_KEY, SCREEN_TEXT_KEY]
            .iter()
            .map(|&k| {
                pack.palette()
                    .get(k)
                    .flatten()
                    .expect("an opaque screen key")
            })
            .collect();
        let px = |x: u16, y: u16| art.get(x, y).copied().flatten();
        for y in SCREEN_GLASS_ROWS {
            for x in SCREEN_GLASS_COLS {
                assert!(
                    px(x, y).is_some_and(|c| screen.contains(&c)),
                    "({x},{y}) is where the glow paints glass, and the art has no glass there"
                );
            }
        }
        let casing_cols = SCREEN_GLASS_COLS.start() - 1..=SCREEN_GLASS_COLS.end() + 1;
        let frame = SCREEN_CASING_ROWS
            .flat_map(|y| casing_cols.clone().map(move |x| (x, y)))
            .chain(SCREEN_GLASS_COLS.map(|x| (x, SCREEN_CHIN_ROW)));
        for (x, y) in frame {
            assert!(
                px(x, y).is_some_and(|c| !screen.contains(&c)),
                "({x},{y}) is where the glow paints the casing or chin, and the art is not casing there"
            );
        }
    }

    fn render(head: Point, phase_ms: u64) -> RgbBuffer {
        let mut buf = RgbBuffer::filled(64, 64, Rgb { r: 0, g: 0, b: 0 });
        let now = SystemTime::UNIX_EPOCH + Duration::from_millis(phase_ms);
        paint_effects(
            &mut buf,
            &crate::effects::sleep_z(head, 0, crate::anim::Motion::Full.beat(now)),
            theme(),
        );
        buf
    }

    fn top_lit(buf: &RgbBuffer, head: Point, bg: Rgb) -> Option<(u16, Rgb)> {
        let zx = head.x + 5;
        (0..head.y).find_map(|y| {
            let p = buf.get(zx, y);
            (p != bg).then_some((y, p))
        })
    }

    #[test]
    fn sleep_z_dims_as_it_rises_then_rests() {
        let head = Point { x: 20, y: 30 };
        let bg = Rgb { r: 0, g: 0, b: 0 };
        let zx = head.x + 5;

        let low = render(head, 200);
        let low_px = low.get(zx, head.y - 3);
        assert!(low_px.lightness() > 0.0, "z near the head is visible");

        let high = render(head, 1600);
        let (top_y, top_px) = top_lit(&high, head, bg).expect("risen z still visible");
        assert!(top_y < head.y - 3, "z rose above its spawn row");
        assert!(
            top_px.lightness() < low_px.lightness(),
            "a higher z must be dimmer than one at the head"
        );

        // 2300 ms lands in the rest gap (phase >= RISE_MS).
        let resting = render(head, 2300);
        for y in 0..resting.height() {
            for x in 0..resting.width() {
                assert_eq!(resting.get(x, y), bg, "no z during the rest gap");
            }
        }
    }
}
